language: python

python:
   - "3.5"

sudo: false

 
install: 
  - pip install pylint

postgresql: "9.3"
  - pip install numpy

before_script:
  - uname -a
  - printenv
  - pip list
  - coverage --version
  - pylint   --version
  - ulimit -s 1082768


script:
  - make tests.tmp