language: python

python:
   - "3.5"

sudo: false

install:
    - pip install -r tools
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install pylint

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version
    - ulimit -s 1082768

script:
    - date
    - ls -al
    - cd Cuibono/
    - make tests.tmp