FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cui Bono 

Cui Bono is the API for our CS373 project which entails creating a web application. The web application is simply a database of the Texan 
bills.

Resources

#GroupBill

Data pertaining to Texan Bills

## Bills Collection [/Bill]

### List All Bills [GET]

+ Response 200 (application/json)

        "bill_list": "A list of all bills ",
            "bills": [
                {
                    "url": "https://cuibono.com/api/bill",
                    "prefix": "House",
                    "Number": "1",
                    "Author": "John otto",
                    "Party": "Republican",
                  }  
                 
                    "Bill Number": [
                        "1",
                        "15"
                        "24"
                    ],
                    " BILL 1" : [
                    "Authors": "John Otto"

                    "Prefix": "House"

                    "Session ID": "84R"

                     "Session Year": "2015"

                    "Sponsors": "Senator Jane Nelson"
                    
                    ],
                     " BILL 15" : [
                    
                   " Authors": "John Otto, Armando Walle"

                    "Prefix": "House"

                     "Session ID": "84R"

                    "Session Year": "2015"

                   " Sponsors": "Senator Kevin Eltife"
                   ],
                   
                    " BILL 24" : [
                    
                   " Authors": "John Otto, Armando Walle"

                    "Prefix": "House"

                     "Session ID": "84R"

                    "Session Year": "2015"

                   " Sponsors": "Senator Kevin Eltife"
                   ],
                    "number": [
                        "https://cuibono.com/api/bills/hb1"
                    ],
                   
                    ],
                    "povbill": [
                        "https://cuibono/api/bills/1",
                       "https://cuibono/api/bills/15",
                        "https://cuibono/api/bills/24", 
                        
                    ],
                    "authors ": [
                     "https://cuibono/api/bills/1",
                     "https://cuibono/api/bills/15",
                     "https://cuibono/api/bills/24",
                    ]
##Contributors Collection [/contributors]

### List All Contributors [GET]

+ Response 200 (application/json)

            "contributors_list": "A list of all contributors ",
            "contributors": [
                {
                    "url": "https://cuibono.com/contributors",
                    "Name": "Border Health PAC",
                    "type": "entity",
                    "city": "Mcalleen",
                    "zipcode": "78504",
                  }  
                 
                    "Name": [
                        "Plumbers Local Union No. 68 PAC Fund"
                        "A&M PAC"
                        "Border Health PAC"
                    ],
                    
                    " Name " : [
                    "Type": Entity"

                  "Website": borderhealthpac.com"

                  "Contributions": Walle: $5,000"

                   "City": McAllen, TX"

                   "Zip": 78504"
                    
                    ],
                     " name" : [
                    
                  
                    "Type": "Entity"

                "Website": "Plumber's PAC"

                "Contributions": "Walle: $2,000"

                     "City": Houston, TX"

                     "Zip": 77249"
                   ],
                   
                    " name " : [
                    
                  
            "Type": "Entity"

           "Website": "tamuspac.org"

           "Contributions": "Davis: $2,500"

           "City": "Austin, TX"

            "Zip": "78768"
                   ],
                    "number": [
                        "https://cuibono.com/api/bills/hb1"
                    ],
                   
                    ],
                    "names": [
                       " http://cuibono.io/contributors/ampac"
                     " http://cuibono.io/contributors/plumberspac"
                     " http://cuibono.io/contributors/borderhealthpac"
                    ],
                    
##legislator Collection [/legislators]
### List All Legislators[GET]

+ Response 200 (application/json)

        [
          "legislators_list": "A list of all legislators ",
            "legislators": [
                {
                    "url": "https://cuibono.com/legislators",
                    "name": "john otto",
                    "party": "Republican",
                    "District": "18",
                    "type": "House of Representative",
                  }  
                 
                    "Party": [
                        "republican",
                        "democrat"
                        
                    ],
                    "district": [
                        "18",
                        "140"
                        "134"
                    ],
                    " Representative John otto" : [
                    "Party": "Republican"

                    "Hometown": "Dayton, TX"

                    "Bills": "House Bill 1, House Bill 15"

                    "Contributors": "No contributors/contributions"
                    
                    ],
                     " Representative Amando Wale " : [
                     "Party": "Democratic"

                   "Hometown": "Houston, TX"

                   "Bills": "House Bill 15"

                    "Contributors": "Border Health PAC, Plumbers Local Union No. 68 PAC Fund"
                   
                   ],
                   
                    " Representative Sarah Davis" : [
                   "Party":" Republican"

                    "Hometown": "Charleston, WVA"

                    "Bills": "House Bill 24"

                    "Contributors": "A&M PAC"
                   ],
                    "number": [
                        "https://cuibono.com/api/bills/hb1"
                    ],
                   
                    ],
                    "Representatives": [
                        "https://cuibono.io/legislators/54588"
                        "http://cuibono.io/legislators/58277"
                        "http://cuibono.io/legislators/66272"
                    ],
        ]
##Contributions Collection [/contributions]
### List All Contributions[GET]

+ Response 200 (application/json)

        [
              "contributions_list": "A list of all contributions ",
            "contributions": [
                {
                    "url": "https://cuibono.com/api/bill",
                    "prefix": "House",
                    "Number": "1",
                    "Author": "John otto",
                    "Party": "Republican",
                  }  
                 
                    ],
                    " Contributions 1" : [
                    "Amount": "$5,000"

                    "Contributor": "Border Health PAC"

                    "legislator": "Armando Walle"

                     "Date": "8-17-2015"
                    
                    ],
                    
                     " Contributions 2" : [
                    "Amount": "$2,500"

                    "Contributor": "A&M PAC"

                    "legislator": "Sarah Davis"

                     "Date": "2-26-2016"
                     
                    ],
                     " Contributions 3" : [
                    "Amount": "$5,000"

                    "Contributor": "Border Health PAC"

                    "legislator": "Armando Walle"

                     "Date": "8-17-2015"
                     ],
                    "Contributor ": [
                     "https://cuibono/api/contributor",
        
                    ]
        ]